# Generated by Django 4.2.2 on 2023-06-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_ena0ble',
            new_name='is_enable',
        ),
    ]
